### ISSUE TITLE
automatic iMessage bridge implementation

### ISSUE THREAD

**Issue by traktuner** [beeper/self-host#11]
Hello,
is there a way you can open-source your implementation of the imessage bridge deployment?
Since it needs to be a macOS system, how does beeper implement this?
Spin up a virtual macOS instance on AWS, deploy the mautrix-imessage bridge on this host -> how do you handle the automatic AppleID login there?
Just curious! Beeper is great, I am using and enjoying it!

**Comment by lucasilverentand** [comment]
I was wondering the exact same thing

**Comment by gabrc52** [comment]
Considering there is a long waitlist they might just do it by hand or some semi-automatic way. I highly doubt they'd open source that since it's a core part of their business.

**Comment by traktuner** [comment]
Since the "old" imessage bridge was discontinued, and the new imessagego brdige will be available on GitHub soon, my request here is obsolete.

**Comment by gabrc52** [comment]
soon... well it was finally open sourced!
