### ISSUE TITLE
Are the clients OSS?

### ISSUE THREAD

**Issue by rokejulianlockhart** [beeper/self-host#24]
If they are, knowing where to locate the source would help https://github.com/beeper/self-host/issues/23#issue-1827553659

**Comment by ericmigi** [comment]
No, sorry they are not

**Comment by rokejulianlockhart** [comment]
Per https://github.com/beeper/self-host/issues/25#issuecomment-1668988776, do you think you could convert this issue to a Q&A discussion for posterity, @ericmigi?
