### ISSUE TITLE
Enable GitHub Discussion.

### ISSUE THREAD

**Issue by rokejulianlockhart** [beeper/self-host#25]
My rationale is available at https://github.com/8go/matrix-commander/issues/68#issue-1237645245. However, more specifically, https://github.com/beeper/self-host/issues?q=is%3Aissue is becoming filled with questions like https://github.com/beeper/self-host/issues/8#issue-1663849821, https://github.com/beeper/self-host/issues/24#issue-1835095237 and https://github.com/beeper/self-host/issues/15#issue-1760483145 instead of issues about https://github.com/beeper/self-host. Enabling GitHub Discussions would allow this to support discuss Beeper slightly more broadly in a Q&A format, which is a frequently necessary precursor to issue creation.

**Comment by ericmigi** [comment]
Good call, enabled!
